from __future__ import annotations

from credit_committee.models import Deal, new_deal_id, utc_now_iso


def sample_deals() -> dict[str, Deal]:
    return {
        "Healthcare services platform": Deal(
            id=new_deal_id(),
            borrower="Northstar Care Partners",
            sponsor="Arden Ridge Capital",
            sector="Healthcare services",
            geography="United States",
            revenue_m=220.0,
            ebitda_m=34.0,
            total_debt_m=168.0,
            purchase_price_m=340.0,
            pricing="SOFR + 625 bps, 1.0% floor, 2.0% OID",
            use_of_proceeds="Sponsor buyout and refinancing of existing debt",
            collateral="First-lien security over substantially all assets and equity pledges",
            covenants="Maintenance leverage covenant with 30% EBITDA cushion and monthly reporting",
            liquidity="18m revolver availability with minimum liquidity covenant",
            thesis="Recurring demand, fragmented local markets, and sponsor playbook for add-on acquisitions.",
            key_risks="Labor availability, reimbursement pressure, acquisition integration, and regional concentration.",
            created_at=utc_now_iso(),
            debt_type="First-lien senior secured term loan plus delayed-draw acquisition facility",
            cash_interest="SOFR + 625 bps cash pay with 1.0% floor",
            amortization="1.0% annual amortization, balance due at maturity",
            maturity="6 years",
            fcf_conversion="55-65% normalized EBITDA to unlevered free cash flow",
            covenant_headroom="30% opening EBITDA cushion under maintenance leverage covenant",
            sponsor_equity_m=172.0,
        ),
        "Industrial software carve-out": Deal(
            id=new_deal_id(),
            borrower="VectorWorks Automation",
            sponsor="Kestrel Partners",
            sector="Industrial software",
            geography="Europe",
            revenue_m=96.0,
            ebitda_m=18.0,
            total_debt_m=112.0,
            purchase_price_m=252.0,
            pricing="EURIBOR + 700 bps, 3.0% OID",
            use_of_proceeds="Corporate carve-out, transition services, and growth investment",
            collateral="Share pledges, IP pledge where available, receivables, and bank accounts",
            covenants="Incurrence-style covenant package with springing liquidity test",
            liquidity="Limited opening cash; relies on revolver availability and transition services continuity",
            thesis="Sticky installed base and mission-critical software embedded in plant workflows.",
            key_risks="Carve-out execution, customer churn, limited standalone financial history, and high leverage.",
            created_at=utc_now_iso(),
            debt_type="First-lien unitranche with springing revolver exposure",
            cash_interest="EURIBOR + 700 bps cash pay with 3.0% OID",
            amortization="Bullet repayment; no scheduled amortization",
            maturity="5.5 years",
            fcf_conversion="40-50% EBITDA to FCF during transition services period",
            covenant_headroom="Springing liquidity test only; limited maintenance leverage protection",
            sponsor_equity_m=140.0,
        ),
    }
